[build-system]
requires = ["hatchling>=1.21.0", "hatch-vcs>=0.3.0"]
build-backend = "hatchling.build"

[project]
name = "xarray-binfile"
description = "Read and write raw binary files using the familiar interface from the Xarray library"
readme = "README.md"
license = "MIT"
requires-python = ">=3.10"
authors = [{ name = "fschuch", email = "me@fschuch.com" }]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python",
]
dynamic = ["version"]
dependencies = ["dask>=2024.0.0", "xarray>=2024.1.0"]

[project.entry-points."xarray.backends"]
binfile = "xarray_binfile.read.entrypoint:RawBinaryEntrypoint"

[project.optional-dependencies]
tests = [
    "coverage[toml]>=7.5.3",
    "hypothesis>=6.130.4",
    "pre-commit>=3.5.0",
    "pytest-benchmark>=5.1.0",
    "pytest-cov>=5.0.0",
    "pytest-memray>=1.7.0; sys_platform != 'win32'",
    "pytest>=8.2.2",
]
tests-extra = [
    "pytest-randomly==3.16.0",
    "pytest-rerunfailures==15.1",
    "pytest-xdist==3.8.0",
]
docs = [
    "docutils==0.21.2",
    "jupyter-book==1.0.4.post1",
    "sphinx-autobuild==2024.10.3",
    "sphinx==7.4.7",
    "sphinx-github-changelog==1.7.1",
]

[project.urls]
Source = "https://github.com/fschuch/xarray-binfile"
Tracker = "https://github.com/fschuch/xarray-binfile/issues"
Changelog = "https://fschuch.github.io/xarray-binfile/references/what-is-new.html"
Documentation = "https://fschuch.github.io/xarray-binfile/"

[project.scripts]

[tool.pytest.ini_options]
addopts = [
    "--benchmark-disable",
    "--doctest-modules",
    "--doctest-continue-on-failure",
    "--doctest-report=ndiff",
]
testpaths = ["tests"]

[tool.coverage.run]
branch = true
relative_files = true
source = ["src/xarray_binfile", "tests"]
omit = ["src/xarray_binfile/_version.py"]

[tool.coverage.report]
precision = 2
show_missing = true
exclude_lines = ["no cov", "if __name__ == .__main__.:", "if TYPE_CHECKING:"]

[tool.ruff]
extend-exclude = ["./docs/conf.py"]

[tool.ruff.lint.extend-per-file-ignores]
"__init__.py" = ["F401"] # imported but unused
"*.ipynb" = ["E402"]     # module level import not at top of file

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.mypy]
pretty = true
ignore_missing_imports = true
exclude = ["docs/conf.py"]

[tool.codespell]
skip = "docs/conf.py"
check-filenames = true
ignore-words-list = ["memmap"]

[tool.hatch.version]
source = "vcs"

[tool.hatch.build.hooks.vcs]
version-file = "src/xarray_binfile/_version.py"

[tool.hatch.envs.default]
description = "Base development environment"
features = ["tests"]
installer = "uv"

[tool.hatch.envs.default.scripts]
pre-commit-install = "pre-commit install {args}"
pre-commit-uninstall = "pre-commit uninstall {args}"
check = "pre-commit run {args} --all-files"
type = "check mypy {args}"
lint = "check ruff {args}"
format = "check ruff-format {args}"
test = "pytest --cov --cov-report=term {args}"
test-benchmark = "test --benchmark-enable --memray {args}"
test-no-cov = "test --no-cov {args}"
qa = ["check", "test", "echo '✅ QA passed'"]

[tool.hatch.envs.test]
description = "Extended test environment"
features = ["tests", "tests-extra"]

[tool.hatch.envs.test.scripts]
extended = "test -n auto --reruns 7 --reruns-delay 1 {args}"

[[tool.hatch.envs.test.matrix]]
python = ["3.10", "3.11", "3.12", "3.13"]

[tool.hatch.envs.docs]
description = "Documentation environment"
template = "docs"
features = ["docs"]
installer = "uv"
python = "3.13"

[tool.hatch.envs.docs.scripts]
config = "jupyter-book config sphinx docs {args}"
build = ["config", "jupyter-book build docs --path-output build {args}"]
serve = [
    "config",
    "sphinx-autobuild docs build/_build/html --open-browser --watch src/xarray_binfile {args}",
]
